/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'beshort' at '8/13/17 6:20 PM' with Gradle 2.14.1
 *
 * @author beshort, @date 8/13/17 6:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
